# This is a basic workflow to help you get started with Actions

name: Analysis

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Python Environment
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7.17

    # Install X-Developer Client
    - name: Install X-Developer Command Line Client
      run: pip install xdclient

    # Runs a set of commands using the runners shell
    - name: Run analysis script
      run: python -m xdclient -i "$APPID" -k "$APPKEY" -t "$TEAMID" -f True
